# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "virtio_pci" "sr_mod" "virtio_blk" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  fileSystems."/" =
    { device = "/dev/disk/by-label/nixos";
      fsType = "btrfs";
      options = [ "rw,noatime,compress=zstd,space_cache,commit=120,subvol=@" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-label/nixos";
      fsType = "btrfs";
      options = [ "rw,noatime,compress=zstd,space_cache,commit=120,subvol=@home" ];
    };

  fileSystems."/.snapshots" =
    { device = "/dev/disk/by-label/nixos";
      fsType = "btrfs";
      options = [ "rw,noatime,compress=zstd,space_cache,commit=120,subvol=@snapshots" ];
    };

  fileSystems."/boot/efi" =
    { device = "/dev/disk/by-label/ESP";
      fsType = "vfat";
      options = [ "rw,noatime" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-label/swap"; }
    ];

}
