# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  
  # Filesystems
  fileSystems."/" =
    { device = "/dev/sda6";
      fsType = "btrfs";
      options = [ "rw,noatime,ssd,compress=zstd,space_cache,commit=120,subvol=@" ];
    };

  fileSystems."/home" =
    { device = "/dev/sda6";
      fsType = "btrfs";
      options = [ "rw,noatime,ssd,compress=zstd,space_cache,commit=120,subvol=@home" ];
    };

  fileSystems."/.snapshots" =
    { device = "/dev/sda6";
      fsType = "btrfs";
      options = [ "rw,noatime,ssd,compress=zstd,space_cache,commit=120,subvol=@snapshots" ];
    };

  fileSystems."/boot/efi" =
    { device = "/dev/disk/by-uuid/061D-C556";
      fsType = "vfat";
      options = [ "rw,noatime" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/ad752a2b-9336-4b90-b04f-b9e9db4001f8"; }
    ];

  nix.maxJobs = 3;
  powerManagement.cpuFreqGovernor = lib.mkDefault "ondemand";
}
